apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-openmetrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-openmetrics-app
  template:
    metadata:
      labels:
        app: nodejs-openmetrics-app
    spec:
      containers:
      - name: nodejs-openmetrics-app
        image: cssonddos/openmetricsjs:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-openmetrics-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/probe: "true"
    prometheus.io/path: "/metrics"
  labels:
    app: nodejs-openmetrics-app
spec:
  selector:
    app: nodejs-openmetrics-app
  ports:
  - name: web
    protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-openmetrics-app
  labels:
    app: nodejs-openmetrics-app
spec:
  selector:
    matchLabels:
      app: nodejs-openmetrics-app
  endpoints:
    - port: web
      #interval: 60s
      path: /metrics
      #scrapeTimeout: 30s
      #targetPort: 80